# Permalinks
permalink:           pretty

# Setup
title:               Atomtong
tagline:             Atomtong
url:                 https://github.com/atomtong/atomtong.github.io
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              atomtong
  url:               https://github.com/atomtong/atomtong.github.io
  email:             676484886@qq.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/atomtong/atomtong.github.io

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist
